# Generated by Django 3.2.4 on 2021-06-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='respondents_particulars',
            field=models.BooleanField(default=False),
        ),
    ]
