# Generated by Django 3.2.4 on 2021-06-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='name_en',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='survey',
            name='name_pl',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='name'),
        ),
    ]
