# Generated by Django 3.2.4 on 2021-06-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_question_respondents_particulars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='respondents_particulars',
            field=models.BooleanField(default=False, verbose_name='Respondents particulars'),
        ),
    ]
