# Generated by Django 3.2.4 on 2021-06-26 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20210626_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='name_pl',
        ),
    ]
