# Generated by Django 3.2.4 on 2021-06-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_question_respondents_particulars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'permissions': (('view_list', 'ViewListPermissionDescription'),)},
        ),
        migrations.AlterField(
            model_name='question',
            name='respondents_particulars',
            field=models.BooleanField(default=False, verbose_name='RespondentsParticularsName'),
        ),
    ]
