# Generated by Django 3.2.4 on 2021-06-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_remove_survey_name_pl'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='name_pl',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='name'),
        ),
    ]
