# Generated by Django 3.2.4 on 2021-06-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20210614_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'permissions': (('view_list', 'Can see survey list \\w questions and available answers'),)},
        ),
        migrations.AddField(
            model_name='question',
            name='multiple_choice',
            field=models.BooleanField(default=False, verbose_name='Multiple choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='respondents_particulars',
            field=models.BooleanField(default=False, verbose_name='Respondents particulars'),
        ),
    ]
