# Generated by Django 3.2.4 on 2021-06-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_alter_survey_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='text',
        ),
    ]
